language: php

sudo: false

php:
  - 5.6
  - 7.0

matrix:
  php: hhvm
    sudo: required
    dist: trusty
    group: edge

  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --no-interaction --prefer-dist --no-progress --profile

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist --verbose --coverage-text="php://stdout"
  - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover
